name: Run Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create a test directory
        run: |
          mkdir -p test-artifacts
          echo "Test artifact" > test-artifacts/test.txt  # Create a dummy file to test upload

      - name: List Test Directory
        run: ls -R test-artifacts  # Check if the file exists

      - name: Upload Test Artifact (v2)
        uses: actions/upload-artifact@v2  # Upload the dummy test artifact directory
        with:
          name: test-artifacts
          path: test-artifacts
