name: Run Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.406'

      - name: Install Allure CLI
        run: |
          sudo apt update
          sudo apt install -y allure

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Project
        run: dotnet build --no-restore

      - name: Run Selenium Tests with Allure Logger
        run: |
          mkdir -p allure-results  # Ensure allure-results directory exists
          dotnet test --logger "allure;allure-results=allure-results" --results-directory TestResults

      - name: List Allure Results Directory
        run: ls -R allure-results  # Debugging: check if allure-results folder is generated

      - name: Upload Allure Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results  # Upload the allure-results directory as an artifact

      - name: Create a Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: TestResults/*

      - name: Upload Test Results as Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: TestResults/*
