name: Run Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  upload_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Test Artifact
        run: |
          mkdir -p my-artifacts
          echo "This is a test artifact" > my-artifacts/test.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifacts
          path: my-artifacts
